### ISSUE TITLE
Sourcemap generation errors

### ISSUE THREAD

**Issue by skerit** [emberfeather/less.js-middleware#104]
The first time the middleware should generate the sourcemap, it fails.
Only after I restart the server will it work again.

Related to this: you can overload the function to store the compiled CSS, but you CAN NOT do this for the sourceMap. So: the sourcemap ends up someplace where it's of no use to anybody.

**Comment by Zoramite** [comment]
Hi @skerit were there any errors that were shown when it couldn't write the sourcemap the first time?

Also, a good point about the sourcemap destination, I'll see if I can work on that problem this weekend.

**Comment by havenchyk** [comment]
Is it reproducible? Issue should be closed otherwise or if there is no any feedback from topic starter
