### ISSUE TITLE
less-middleware and Node.js strict mode

### ISSUE THREAD

**Issue by iamakulov** [emberfeather/less.js-middleware#106]
Hello!

If there's an Node.js application which uses `less-middleware` and you run it with Node's `--use-strict` option, you get the following error:

```
> node --use-strict bin\www

...\node_modules\less-middleware\node_modules\mkdirp\index.js:9
        mode = 0777 & (~process.umask());
               ^^^^
SyntaxError: Octal literals are not allowed in strict mode.
```

Please consider fixing it.

Thank you.

**Comment by Zoramite** [comment]
Looking at the `mkdirp` dependency they have changed how they make the mode so hopefully that fixed this issue. If not you can report the issue on their repository here: https://github.com/substack/node-mkdirp
