### ISSUE TITLE
Less 2.2.0

### ISSUE THREAD

**Issue by jerone** [emberfeather/less.js-middleware#114]
Any change in updating :arrow_up: the Less dependency to the [latest version](https://github.com/less/less.js/blob/master/CHANGELOG.md): 2.2.0...

**Comment by Zoramite** [comment]
Just tested to see if we could do a quick dependency change and be ok: 
https://drone.io/github.com/emberfeather/less.js-middleware/46

Looks like it will need to have some work down to support 2.2.0. If you would like to try your hand at I can review a Pull Request for you.

**Comment by jerone** [comment]
That probably requires a little bit knowledge about Less and Express then that I have right now. To bad it wasn't an easy fix.

**Comment by benirose** [comment]
What's the status on this pull request?

https://github.com/emberfeather/less.js-middleware/pull/115

**Comment by Zoramite** [comment]
@benirose I didn't have time initially to find out the changes that happened with the jump to 2.x and fix them. I'm planning on looking at it more this weekend, but if you have time to see what is broken and run the tests then pull requests are welcome :smile:

**Comment by benirose** [comment]
Haha, I didn't realize the PR was just a dependency change. I'll try to get something together.

**Comment by Zoramite** [comment]
Closed by #115 and release 2.0.0
