### ISSUE TITLE
Feature: create and serve different versions of css based on browsers!

### ISSUE THREAD

**Issue by techsin** [emberfeather/less.js-middleware#116]
Is it possible to have this produce prefixed css if i want to. And create 4 separate files. One that contains all prefixed versions, other three based on browsers moz, webkit, etc. Then using middleware, this one or new/other one, it configure express to detect browser using user agent and then send appropriate file accordingly, if something is amiss or unclear then just send the default version which has all files. 

This would not necessarily save developers the time but speed up the websites. So instead of sending same code times 2.5 we will be sending only 1. And instead of using autoprefixer or prefixfree or running some last minute prefixer command in grunt, we will be generating smart prefixed files once, automatically.

This goes best functionality such as compression that less middleware already offers.

Thanks for reading this..

**Comment by Zoramite** [comment]
The first issue that I see with custom prefixed css is that there is no native (that I am aware of) way to determine the correct prefixes for each browser and map those to the official un-prefixed css. Some of them are not just name changes but also handle the differently to accomplish the same thing. For example, go explore gradients and you will find several ways of creating them based on browser.

I believe that you could create a mi\xin to handle the ones that require prefixing and not have to copy-paste the prefixes each time.

That doesn't help with file size, but you can turn up the compression to get rid of some of the whitespace and make your file sizes smaller.

**Comment by Zoramite** [comment]
Also, just noticed this nice plugin for less that should work with the middleware now: 

https://github.com/less/less-plugin-autoprefix

See: http://stackoverflow.com/a/28655272/1172228
