### ISSUE TITLE
How do you use plugins with less middleware...(google/SO dont know)

### ISSUE THREAD

**Issue by techsin** [emberfeather/less.js-middleware#119]
EX: https://github.com/less/less-plugin-autoprefix  this plugin prefixes css and is used like this.
```
less.render(lessString, { plugins: [autoprefixPlugin] })  .....
```
but in express using this middleware we do like this...
```
app.use(require('less-middleware')(path.join(__dirname, 'public'),{ compiler:{sourceMap:true}});
```
i have tried passing `plugins: [autoprefixPlugin]`  as an option after compiler property but it seems to have no effect. And in docs of lessjs middleware doesn't have any mention of plugins property either. 

It'd be nice to answer here as it might help more people:

http://stackoverflow.com/questions/28638139/in-express-how-to-specify-option-for-prefix-plugin-for-less

**Comment by Zoramite** [comment]
Thanks, I am actually working on updating less-middleware *right now* to support the latest version of less. I don't know if I will finish it today, but I am working on it in #115
