### ISSUE TITLE
LESS File error *.less wasn't found

### ISSUE THREAD

**Issue by Martii** [emberfeather/less.js-middleware#122]
Upon testing the latest package of [2.0.0](/emberfeather/less.js-middleware/releases/tag/2.0.0) here we get this in our dev console.

``` sh-session
  LESS File error : 'variables.less' wasn't found. Tried - ~/repo/git/oujs/martii/OpenUserJS.org/public/less/bootstrap/variables.less,variables.less
  LESS File : ~/repo/git/oujs/martii/OpenUserJS.org/public/less/bootstrap/oujs.less 4:0

...

GET /less/bootstrap/oujs.css 500 1485.903 ms - -
```

See also:
* Our implementation at [/app.js#L108-L117](https://github.com/OpenUserJs/OpenUserJS.org/blob/1239e562b8c8156b68803144131c347626156444/app.js#L108-L117) e.g. we currently combine the contents of [our local pathed /public/less/bootstrap](https://github.com/OpenUserJs/OpenUserJS.org/tree/1239e562b8c8156b68803144131c347626156444/public/less/bootstrap) and the [their local pathed /less](https://github.com/twbs/bootstrap/tree/master/less) items with a `path` lookup for `@import` *([this projects doc ref](/emberfeather/less.js-middleware/wiki/Examples#importing-less))*.

Any ideas on what broke? Many thanks.

Related:
* #115 
* #114

**Comment by Martii** [comment]
Appears to be ignoring the `compiler` option to not `compress` as well.

**Comment by Zoramite** [comment]
Hello, I believe that paths is now part of the `render` option. So I would change your code to something like this and see if it works:

    app.use(lessMiddleware(__dirname + '/public', {
      render: {
        compress: false,
        paths: [
          path.join(__dirname, 'node_modules/bootstrap/less')
        ]
      }
    }));

**Comment by Martii** [comment]
> ... `paths` is now part of the `render` option. ..

Awesome... that appears to work on our dev... time to go test on production. I was dreading using relative urls as the alternative. ;) Thank you so much. :)
