### ISSUE TITLE
@import doesn't work (file not found)

### ISSUE THREAD

**Issue by hohl** [emberfeather/less.js-middleware#125]
I've just setup a tiny app utilizing this middleware (with latest 2.0.1 release) like described in your `README.md`:

    var publicPath = path.join(__dirname, 'public');
    app.use(lessMiddleware(publicPath, {
        pathRoot: publicPath,
        render: {
            paths: [publicPath]
        }
    }));
    app.use(express.static(publicPath));

Then I created two files in `public/stylesheets` called `site.less` and `variables.less`. Fetching of `stylesheets/site.less` works fine. Everything gets compiled, however if I add:

    @import "variables"

it prints me an error (in web browser) telling me that less can't find "variables.less".

*Then I tried setting the path of the middleware module directly to the stylesheets folder, but this doesn't help. Using `@import "stylesheets/variables"` instead doesn't help too. I don't have any idea, how I could could get fixed. :(*

Any idea, what I made wrong?

**Comment by hohl** [comment]
And here is the full error message I get when fetching the `site.less` (with `@import "variables"` included) file in browser:

    {"type":"File","filename":"input","index":0,"line":1,"callLine":null,"column":0,"extract":[null,"@import \"variables\";",""],"message":"'variables.less' wasn't found. Tried - variables.less,variables.less"}

**Comment by hohl** [comment]
The issue seem to be that I tried to fetch `site.less`. If I fetch `site.css` it works. I also noticed that fetching `site.less` doesn't log anything, while I see some logging when fetching `site.css` (debug=1 passed as option to the middleware of course).

**Comment by Zoramite** [comment]
The middleware is made to watch for `.css` requests and look for the corresponding `.less` file to compile and return as the css. Normally you don't request the `.less` file directly, just the `.css` file and it just 'works'.

Is there a specific reason that you are requesting the `.less` file?

**Comment by hohl** [comment]
No, I just hadn’t any idea about that I should use *.css. Maybe you want to add that to the `README.de`

But thanks for that lib, great work.
