### ISSUE TITLE
Replacement for dumpLineNumbers option in v 2.*.*

### ISSUE THREAD

**Issue by emmettnicholas** [emberfeather/less.js-middleware#129]
I'm interested in upgrading from 1.0.4.

Is there a new syntax for the old parser option

    dumpLineNumbers: 'comments'

?

**Comment by Zoramite** [comment]
The `dumpLineNumbers` should still work, you just need to pass it into the less renderer. Try something like this:

    {
      'render': {
        'dumpLineNumbers': true
      }
    }
