### ISSUE TITLE
Publish npm for upgrade to Less 2.5.x

### ISSUE THREAD

**Issue by waynebloss** [emberfeather/less.js-middleware#137]
Hello, I see that you have a commit that upgrades Less to v2.5.x, but it remains unpublished in npm.

Would you please advise me if you are going to publish this change soon?

Thanks for your work.

**Comment by DamonGant** [comment]
Yep, I've started getting warnings for the graceful-fs version pulled being unsupported in Node 7 and this package depending on an old LESS version is the culprit.

**Comment by Zoramite** [comment]
Thanks for the reminder, I've published 2.2.0 with the latest dependencies updated.
