### ISSUE TITLE
npm WARN deprecated graceful-fs@3.0.8:

### ISSUE THREAD

**Issue by Martii** [emberfeather/less.js-middleware#140]
``` sh-session
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

Related to [`7c43db3`/package.json#L12](https://github.com/emberfeather/less.js-middleware/blob/7c43db302063efde8fa4d8154a76531d7d93d0d7/package.json#L12)

Refs:
* [Upstream repo](https://github.com/less/less.js) [current graceful`1bc481b`/package.json#L40](https://github.com/less/less.js/blob/1bc481bb9ade9ae27394c2cef25265608fc2c5c8/package.json#L40)
* [![less](https://img.shields.io/npm/v/less.svg?style=flat)](https://www.npmjs.com/package/less)

Not quite sure what this entails for this package. No known failures yet... but is in the console none-the-less.

TIA

**Comment by Zoramite** [comment]
HI @Martii 
This looks like an issue for a dependency on the less package itself. You can open an issue on the [Less](https://github.com/less/less.js) repo since we just depend on them as a dependency and not directly on graceful fs. There is also one other dev dependencies that depend on it as well that may also generate the warning: [mocha](https://github.com/mochajs/mocha) is depending on an old version of glob which depends on an old version of graceful-fs.

**Comment by Martii** [comment]
@Zoramite 
Thanks... ~~something that is confusing though is~~ the clean `$ npm install` here...

``` sh-session
less-middleware@2.0.1 node_modules/less-middleware
├── node.extend@1.1.5 (is@3.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
└── less@2.4.0 (mime@1.3.4, graceful-fs@3.0.8, image-size@0.3.5, errno@0.1.4, promise@6.1.0, source-map@0.2.0)
```

and with your latest version bump here with https://github.com/emberfeather/less.js-middleware/commit/e8f21630339da8ad80ca64a46a35b8087faedc37 and another `$ rm -Rf node_modules` then `$ npm install`:

``` sh-session
less-middleware@2.1.0 node_modules/less-middleware
├── node.extend@1.1.5 (is@3.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
└── less@2.6.0 (mime@1.3.4, graceful-fs@3.0.8, image-size@0.3.5, errno@0.1.4, promise@6.1.0, source-map@0.4.4)
```

Ahh I see GH repo is ahead of 2.6.0 but not denoted, plus they don't have [a newer 2.6.0 release/tag yet](https://github.com/less/less.js/releases) and that's where they are updated already with the newer *graceful-fs*. [this posts most current `4bd5878`/package.json](https://github.com/less/less.js/blob/4bd587818c094acfcbfa9c462e3464266f2430b8/package.json#L3) for *less*. Think I'm going to have to directly check the folders from now on to confirm if npmjs.com  *less* is in sync with their repo... I have a feeling this won't be the last time this happens.

Thanks for the clarification and the additional tips... and apologies for the noise. :) Keep up the great work. :)
