### ISSUE TITLE
how to generate source maps?

### ISSUE THREAD

**Issue by admdh** [emberfeather/less.js-middleware#143]
Hi, i can't figure out how to generate source maps, can anyone help me with that?
Currently i have this config:
```
app.use('/static/', lessMiddleware(__dirname + '/static/', {
	force: true, 
	postprocess: {
		sourcemap: true
	}
}));
```
but this doesn't work.. What am i doing wrong?

**Comment by Zoramite** [comment]
Can you try it passing the sourcemap options into the render option?

    app.use('/static/', lessMiddleware(__dirname + '/static/', {
        force: true, 
        render: {
            sourceMap: {}
        }
    }));

**Comment by admdh** [comment]
Great! it works, and how it's possible to render inline sourceMap?

**Comment by Zoramite** [comment]
sourceMap: {
      sourceMapFileInline: true
    }

Like that?
