### ISSUE TITLE
Add function to alter settings after initiation.

### ISSUE THREAD

**Issue by ackwell** [emberfeather/less.js-middleware#70]
Quite a few frameworks (such as Locomotive, and some homebrews) separate configuration into different files depending on the current `NODE_ENV`, however `less-middleware` can only be configured via the constructor.

If a function or other could be added that allows the middleware's options to be set post-initialisation, I believe it'd come in handy.

**Comment by Zoramite** [comment]
So it seems to me that you should just be able to pass in a different set of options depending on the environment to your initial creation of the `app.use`. This doesn't really require per request modification of the settings, but rather a different initial set of settings depending on environment.
