### ISSUE TITLE
Importing font-awesome package breaks fonts

### ISSUE THREAD

**Issue by Cysioland** [emberfeather/less.js-middleware#74]
Hi,
I try to import font-awesome npm package, using
```JavaScript
paths: [path.join(__dirname, 'node_modules', 'font-awesome', 'less')],
relativeUrls: true
```
and still fonts are broken. Just displaying squares.
It searches for font in noder_modules/font-awesome/fonts, but it doesn't find it, since it isn't published by server. How to fix that issue?

**Comment by tomatau** [comment]
Thanks @suy for your working instructions.

@Cysioland - trying to implement `render: [ paths ]` for a similar goal but struggling to debug. How can I see which paths have been added to less' compilation and import process? If I attempt some logging in the importPaths function I get no output and my debugger isn't triggered.

NB. Using koa-less which is just a wrapper around this lib.
