### ISSUE TITLE
Provide HISTORY.md file

### ISSUE THREAD

**Issue by ryandesign** [emberfeather/less.js-middleware#82]
Please provide a HISTORY.md file in which you document what changed in each version. I am currently updating a web site I developed over a year ago, and it's unclear how I should otherwise find this information.

**Comment by Zoramite** [comment]
You can use the history part of the github site to see the past releases and roughly what has changed. Or you can see the actual commits between releases if you are really interested in what has changed: https://github.com/emberfeather/less.js-middleware/releases
